// Generated by scripts/gen-variants.mjs from lib/tools.ts — do not edit by hand.
import { ToolPageShell } from "@/components/ToolPageShell";
import { toolMetadata } from "@/lib/i18n/tool-meta";
import content from "@/content/tools/flip-image.pt";
import parent from "@/content/tools/rotate-image.pt";
import { RotateTool } from "@/app/rotate-image/RotateTool";

export const metadata = toolMetadata(content);

export default function Page() {
  return (
    <ToolPageShell content={content} parent={parent}>
      <RotateTool preset={{ flipH: true }} />
    </ToolPageShell>
  );
}
