// Generated by scripts/gen-variants.mjs from lib/tools.ts — do not edit by hand.
import { ToolPageShell } from "@/components/ToolPageShell";
import { toolMetadata } from "@/lib/i18n/tool-meta";
import content from "@/content/tools/discord-banner-resizer.pt";
import parent from "@/content/tools/resize-image.pt";
import { ResizeTool } from "@/app/resize-image/ResizeTool";

export const metadata = toolMetadata(content);

export default function Page() {
  return (
    <ToolPageShell content={content} parent={parent}>
      <ResizeTool preset={{ platform: "discord", preset: "Profile banner" }} />
    </ToolPageShell>
  );
}
