// Generated by scripts/gen-variants.mjs from lib/tools.ts — do not edit by hand.
import { ToolPageShell } from "@/components/ToolPageShell";
import { toolMetadata } from "@/lib/i18n/tool-meta";
import content from "@/content/tools/image-to-hd.pt";
import parent from "@/content/tools/upscale-image.pt";
import { UpscaleTool } from "@/app/upscale-image/UpscaleTool";

export const metadata = toolMetadata(content);

export default function Page() {
  return (
    <ToolPageShell content={content} parent={parent}>
      <UpscaleTool preset={{ scale: 2 }} />
    </ToolPageShell>
  );
}
