// Generated by scripts/gen-variants.mjs from lib/tools.ts — do not edit by hand.
import { ToolPageShell } from "@/components/ToolPageShell";
import { toolMetadata } from "@/lib/i18n/tool-meta";
import content from "@/content/tools/3x4-photo.id";
import parent from "@/content/tools/passport-photo-maker.id";
import { PassportPhotoTool } from "@/app/passport-photo-maker/PassportPhotoTool";

export const metadata = toolMetadata(content);

export default function Page() {
  return (
    <ToolPageShell content={content} parent={parent}>
      <PassportPhotoTool preset={{ size: "3x4" }} />
    </ToolPageShell>
  );
}
