// Generated by scripts/gen-variants.mjs from lib/tools.ts — do not edit by hand.
import { ToolPageShell } from "@/components/ToolPageShell";
import { toolMetadata } from "@/lib/i18n/tool-meta";
import content from "@/content/tools/instagram-grid-maker.hi";
import parent from "@/content/tools/split-image.hi";
import { SplitTool } from "@/app/split-image/SplitTool";

export const metadata = toolMetadata(content);

export default function Page() {
  return (
    <ToolPageShell content={content} parent={parent}>
      <SplitTool preset={{ mode: "instagram" }} />
    </ToolPageShell>
  );
}
