// Generated by scripts/gen-variants.mjs from lib/tools.ts — do not edit by hand.
import { ToolPageShell } from "@/components/ToolPageShell";
import { toolMetadata } from "@/lib/i18n/tool-meta";
import content from "@/content/tools/jpg-to-pdf-under-500kb.hi";
import parent from "@/content/tools/image-to-pdf.hi";
import { ImageToPdfTool } from "@/app/image-to-pdf/ImageToPdfTool";

export const metadata = toolMetadata(content);

export default function Page() {
  return (
    <ToolPageShell content={content} parent={parent}>
      <ImageToPdfTool preset={{ maxKb: 500 }} />
    </ToolPageShell>
  );
}
