// Generated by scripts/gen-variants.mjs from lib/tools.ts — do not edit by hand.
import { ToolPageShell } from "@/components/ToolPageShell";
import { toolMetadata } from "@/lib/i18n/tool-meta";
import content from "@/content/tools/compress-image-to-150kb.pt";
import parent from "@/content/tools/compress-image.pt";
import { CompressTool } from "@/app/compress-image/CompressTool";

export const metadata = toolMetadata(content);

export default function Page() {
  return (
    <ToolPageShell content={content} parent={parent}>
      <CompressTool preset={{ targetKb: 150 }} />
    </ToolPageShell>
  );
}
