// Generated by scripts/gen-variants.mjs from lib/tools.ts — do not edit by hand.
import { ToolPageShell } from "@/components/ToolPageShell";
import { toolMetadata } from "@/lib/i18n/tool-meta";
import content from "@/content/tools/blur-background.pt";
import parent from "@/content/tools/remove-background.pt";
import { RemoveBgTool } from "@/app/remove-background/RemoveBgTool";

export const metadata = toolMetadata(content);

export default function Page() {
  return (
    <ToolPageShell content={content} parent={parent}>
      <RemoveBgTool preset={{ background: "blur" }} />
    </ToolPageShell>
  );
}
