/* GENERATED by scripts/build-icon-font.mjs — do not edit. */
/** Hashed URL of the self-hosted Material Symbols subset, for <link rel="preload">. */
export const ICON_FONT_URL = "/fonts/material-symbols-outlined-b5aca6e7.woff2";
